### ISSUE TITLE
Почему используется SQL?

### ISSUE THREAD

**Issue by konard** [rimsleur/qsl#1]
В данный момент я занимаюсь разработкой NoSQL базы данных, которая вероятно могла бы быть заменой для SQL в этом контексте.
Можно чуточку глубже описать в чём суть проекта?

**Comment by rimsleur** [comment]
Добрый день. SQL тут просто как инструмент.
Цель проекта ислледовать возможность программирования объяснением в 
процессе коммуникации, т.е. без доступа к исходному коду. Достичь этого 
планируется путем совмещения двух идей:
- Язык программных инструкций должен не только отражать операции с 
  объектами кода, а и быть способным к передаче информации, способным к 
  переходу на разные уровни абстракции.
- Язык не должен содержать инструкций условных переходов и циклов 
  непосредственно. Программирование осуществляется способом более 
  свойственным мышлению человека -- описанием ситуаций. В комментариях 
  указали ссылку на мою предыдущую статью, в которой этот принцип 
  раскрывается.

10.10.2015 01:46, Konstantin Dyachenko пишет:

**Comment by konard** [comment]
> В комментариях 
> указали ссылку на мою предыдущую статью, в которой этот принцип
> раскрывается.

Не могу найти ссылку, можно её продублировать?

**Comment by rimsleur** [comment]
http://habrahabr.ru/post/266829/

12.10.2015 15:15, Konstantin Dyachenko пишет:

**Comment by konard** [comment]
Очень схоже с тем, в каком русле я сейчас делаю свои исследования. Но первым шагом для себя я выбрал создание максимально самостоятельной системы, и на текущий момент есть уже готовая база данных (рекурсивный граф в двух вариантах, пары и триплеты) - https://github.com/Konard/LinksPlatform , если будет возможность пообщаться, возможно наши труды можно будет объединить.

**Comment by rimsleur** [comment]
Я так понял вы работете над неким инструментом. Какова его цель? В каких 
ситуациях и для чего вы бы его использовали? Такой пример: я 
разрабатываю интерпретатор, чтобы самому же его дальше и использовать и 
попытаться применить его сильные стороны (если такие будут выявлены) на 
практике, для более упрощенного описания сложных (объемных, с тысячами 
ветвлений) алгоритмов (таких как база знаний, чат-бот, программирование 
игрового поведения персонажей, программирование робота). В какой сфере 
можно применить вашу разработку, и собираетесь ли вы что-то создавать на 
ее основе?

14.10.2015 04:30, Konstantin Dyachenko пишет:

**Comment by konard** [comment]
Это универсальная платформа (в данный момент это можно называть базой данных), да, я планирую сделать чат-бота на ней. А также загружать знания из Wikipedia, GitHub для обработки, например можно реализовать автоматический перевод по смыслу со всех человеческих языков на все человеческие языки, также можно реализовать автоматический переводчик формальных языков программирования, который автоматически модифицирует код, подстраивает его под каждое окружение. Далее генерация кода, развитие и т.п. Всё что угодно от простейшей тьюринг машины до искусственного интеллекта можно пробовать :)

**Comment by rimsleur** [comment]
Про переводчик я забыл написать. Тоже очень интересное направление. 
Вобщем-то задачи схожи, но реализация разная. Честно говоря, трудно 
представляю, как можно объединить усилия. Инструмены разные (у меня 
Питон, у вас Шарп), подходы разные (от языка с валентностями я врядли 
откажусь..).
Будет ли интерпретатор? Для чат бота нужно задавать правила, как и для 
переводчика и для всего остального. Как это будет работать, будет свой 
встроенный язык?

**Comment by konard** [comment]
Да интерпретатор будет. Сама структура данных (Links) является не только формой хранения, но и расширяемым языком / протоколом передачи данных. Валентности в этом языке возможны, но не обязательны.

**Comment by rimsleur** [comment]
Трудно себе это представить. Есть где-нибудь описание за счет чего 
достигается такая гибкость?

**Comment by konard** [comment]
За счёт простоты и единообразия, вся база данных состоит из мельчайших кусочков - связей. И нет ровным счётом никаких других типов, но этого достаточно, чтобы хранить информацию в любой форме, структурировано и нет.

**Comment by rimsleur** [comment]
Ок, это уровень базы данных. Уровень языка это следующий уровень 
конкретики, который должен описывать конструкции языка и правила их 
построения. Потом, на основе этих правил можно строить интерпретатор. 
Насколько я понимаю этот уровень пока не описан.
Идея ассоциативной БД неплохая, в ней что-то есть, но я пока не понял, 
что именно и как это можно использовать. У меня SQL база данных просто 
как инструмент для хранения всего в одном месте. SQL-инструкциями 
пронизан код, просто так на нереляционную БД уже не перейти, вернее есть 
другие пока что более важные задачи.

**Comment by konard** [comment]
Тогда предлагаю гонку, кто быстрее решит заявленную проблему :) А именно программирование системы путём общения с системой. Правда я скорее всего буду использовать самообучение на основе ранее существующего исходного кода в интернете, так что это возможно будет не совсем честная гонка.

**Comment by rimsleur** [comment]
Ок :) Но у меня несколько разных проектов и между ними приходится 
переключаться.

20.10.2015 00:12, Konstantin Dyachenko пишет:
